### ISSUE TITLE
Combining resources

### ISSUE THREAD

**Issue by AdamLindt** [Wyamio/Wyam#76]
So I spent a good portion of the day trying to find a .NET-based static site generator to replace a Jekyll site and haven't really found one that checks all the boxes, so to speak. There is a bunch of projects ([here](https://github.com/search?l=C%23&o=desc&q=static+site&s=updated&type=Repositories&utf8=%E2%9C%93), [here](https://github.com/search?l=C%23&o=desc&q=jekyll&ref=searchresults&s=updated&type=Repositories&utf8=%E2%9C%93) and [here](https://github.com/search?utf8=%E2%9C%93&q=static+site+language%3AF%23&type=Repositories&ref=searchresults)) in half-finished state but none that come close to replacing Jekyll, Pelican or Hugo or any of the other well known static site generators. Wyam was probably the most mature solution I found (in terms of features, not necessarily age) but it still is missing quite a few features. It seems like a waste to have all of these competing efforts that don't really get finished. I am just opening this issue to see if folks are interested in merging efforts (with Wyam) instead. 

Absolute worst case scenario, I figure there might be interest in coming up with common format for themes, plugins, etc. to be shared.

//cc

@Benjamindudok
@GarethLowe
@Theodus2009
@lukevenediger
@dswisher
@daveaglick 
@pgrzmil
@cody82
@robmen
@PhilipDaniels 
@mikoskinen
@Kelindar 
@adamkrieger 
@bcwood
@andagr
@smack0007
@idiotandrobot
@Jaykul
@olegsych
@nukedbit
@mattweldon
@dragan
@bramdemoor
@ipavl
@dodyg
@WangYuanCI

**Comment by AdamLindt** [comment]
Also adding @dustinmoris, @behizm, @etkirsch, @Allen-Wei, @pspfolio, @Pavuucek

**Comment by daveaglick** [comment]
First off, thanks for the kind words. I appreciate the sentiment, and would certainly welcome anyone who's interested in getting involved (just ask @dodyg, my main partner in crime so far). Wyam is designed to be highly modular and extensible so that new functionality can be layered on top with minimal coordination and impact to other modules. For anyone who's interested, a good starting guide is here:

http://wyam.io/knowledgebase/writing-a-module

I guess my first question would be: what functionality that is currently present in Jekyll, Pelican, Hugo (or other site generators) do you feel is missing? Are those missing features covered in one or more of the existing issues (you'll notice there are a lot - basically all potential modules get tracked as an issue first). If not, a good first step is to create an issue to track any features you (or others) see missing.

Incidentally, the current issues are also a good way to see where contributions would be helpful. Because the system is so modular, it's easy to jump right in and create a new module for something. It's really easy and I'd be happy to walk anyone though the process. I eventually envision a core set of "official" modules with an extended set of community-driven ones.

I'd also like to point out two excellent existing .NET static site generators that aim to replicate all (or most) of the existing Jekyll functionality. I certainly don't want to discourage participation in Wyam, but perhaps one of these may get you up and running quickly if you haven't already run across them:
- [Pretzel](https://github.com/Code52/pretzel)
- [Snow](https://github.com/Sandra/Sandra.Snow)

**Comment by ipavl** [comment]
Previous similar discussion for reference: https://github.com/Code52/pretzel/issues/227

**Comment by daveaglick** [comment]
I think the challenge for this kind of collaboration is well summed up near the end of the linked discussion. Each static site generator is created with a specific set of goals, and the underlying architecture is necessarily designed to support those goals. Even though "static site generation" is a specific kind of project, it's no easier to find redundancies and opportunities for code and architecture sharing than it would be in any other broad category of library like JSON parsers or dependency injection frameworks. The devil is in the details, as they say.

For example, Wyam is designed from the ground-up to be modular and flexible. It can almost be thought of more as a static generation toolbox or "static site generator generator" than a blogging engine. That design comes at the expense of other goals like initial simplicity. Compare that to other site generators that are designed with very different primary goals, where perhaps simplicity is the primary driver. The projects would have very different architectures and a very different view of things. Neither is *better*, just intended for different use cases.

I think where a discussion like this *can* be valuable is in building a broader community around the concept of static generation. Seeing where the pain points are, figuring out what people want and need from generators, and sharing ideas and strategies. In my opinion the area is primed for innovation, and I would love to see some .NET projects gain traction (even if they're not my own).

**Comment by dragan** [comment]
I have to agree with @daveaglick, [mulder](https://github.com/dragan/mulder) was created out of my need for a documentation generator. I based it off of [nanoc](http://nanoc.ws/). I mainly created it for my use case, as there wasn't really anything at the time that could do the same thing. I got it to a working state for my needs and haven't needed to update it, even though that will change soon.

**Comment by dodyg** [comment]
@daveaglick is an awesome maintainer. He's very helpful in guiding newbie to the project and responsive to feedback.

I see wyam as a Data Transformation Service cloaked in Static Site Generator clothing. The good thing about this model is that nobody needs any permission or gain consensus to build the necessary modules that operate on the input, output or transformation part of the pipeline.

**Comment by AdamLindt** [comment]
@ipavl thanks for the link. So it looks like I am not the only one to have this thought. Although it doesn't look like it was too successful there...

@daveaglick Yea, most of the things that I needed are logged as issues (like #71/#30, #66, #44, etc.) but there are things like comments, themes, etc. that are not. But the impetus for me creating this issue was the fact that Wyam is modular and plug-in based. It seemed to me like it would allow features to included as modules and thus it can be as basic or as opinionated as people wanted it to. I understand in some cases people will opt for simplicity and prefer a solution tailor-made for their uses but generally speaking, I didn't see anything that specific/unique while I was browsing through the other repos. In fact, I would say a majority of them were also built with modularity/extensibility as an explicit goal. My question is, why can not happen in a collaborative environment vs being done in individual silos?

**Comment by andagr** [comment]
I also agree with the linked diskussion. [Firm](https://github.com/andagr/Firm) was created out of my specific need and interest. But i do welcome ideas on e.g. common template formats. Razor seems a bit heavy, (DotLiquid)[http://dotliquidmarkup.org/] seems promising and I think that has been mentioned in FsBlog as well.

**Comment by MaximRouiller** [comment]
Quick question then...

Could those project be based off Wyam or would that be too complicated? Wyam seem to be "generic" and all those other frameworks are very specific to a need. The only thing missing is the integration (oversimplifying a lot). 

Does that make sense?

**Comment by daveaglick** [comment]
@MaximRouiller Short answer: yes. The way Wyam has been architected, it's intentionally generic and I would guess that just about any type of static content generator could be represented with a mix of in-built and custom modules. If not now, then some future enhancements like DotLiquid support (on the near horizon - see #10), recipes, themes, etc. will make this even easier. And if a module is built to be generic, it could indeed benefit everyone. This gets back to the idea of Wyam as a static generator generator (as opposed to a static generator in it's own right). In this perspective, the config file just serves as one of many ways to "develop" your custom static generator (as would embedding the Wyam engine in a custom application). In fact, I've got it in the back of my mind that once I get modules in place for some key Jekyll concepts like Liquid (via DotLiquid), I may make a separate "Wyam application" (or at least a recipe - see #1) for generating Jekyll sites without (much) modification.

However, I'm going to guess that most/all of these other projects have their own reasons why this approach wouldn't be appropriate for them (it was built to learn, already works well, don't like the dependency, etc.). Which is all great - having a rich set of somewhat similar projects gives a broader range of ideas to get inspired by.

That said, I'd welcome anyone who wants to generate new tools by using Wyam as an engine rather than a "product". This scenario was envisioned from the start and is why the actual `wyam.exe` is just a shell around a library that can be included elsewhere.

**Comment by daveaglick** [comment]
I'm going to go ahead and close this issue for now since we've heard from several of the folks mentioned in the original post. Once again, I'd be happy to welcome and support anyone who wants to jump in and I'd be happy to discuss any synergistic opportunities or design ideas (did I just say "synergistic opportunities"?!).
